config/routes.rb
Rails.application.routes.draw do
  get 'comments/new'

  get 'comments/create'

  resources :cocktails do
    resources :doses, only: [:new, :create]
    resources :comments, only: [:new, :create]
  end

  resources :doses, only: [:destroy]
  root to: 'cocktails#index'
  get 'profile', to: 'cocktails#profile'
  get 'search', to: 'cocktails#search'
  mount Attachinary::Engine => "/attachinary"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  has_many :votes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_attachments :photos, maximum: 2

  validates :name, uniqueness: true, presence: true

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :cocktail
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :description, presence: true
  validates :cocktail, uniqueness: { scope: :ingredient }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses

  validates :name, uniqueness: true, presence: true
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :cocktail
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.last(4)
  end

  def search
    @cocktails = Cocktail.all
    if params[:search]
      @cocktails = Cocktail.search(params[:search], order: :name)
    else
      @cocktails = Cocktail.all.order("created_at DESC")
    end
  end

  def show
    @cocktail = Cocktail.find(params[:id])
    @cocktails_similar = Cocktail.all
  end

  def new
    @cocktail =  Cocktail.new
  end
  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def edit
    @cocktail = Cocktail.find(params[:id])
  end

  def update
    @cocktail = Cocktail.find(params[:id])
    @cocktail.update(cocktail_params)
    redirect_to cocktail_path(@cocktail)
  end

  def destroy
    @cocktail = Cocktail.find(params[:id])
    @cocktail.destroy
    redirect_to :back
  end

  def profile
    @cocktails = Cocktail.all
  end

  private
  def cocktail_params
    params.require(:cocktail).permit(:name, :category, :alcoholic, :glass, :instructions, :difficulty, photos: [])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @comment = Comment.new
  end

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @comment = @cocktail.comments.new(comment_params)
    has_been_saved = @comment.save

    if has_been_saved
      redirect_to cocktail_path(id: @cocktail.id)
    else
      # raise "Dose could not be saved because #{@dose.errors.full_messages}"
      render :new
    end
  end

  def comment_params
    params.require(:comment).permit(:comment)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = @cocktail.doses.new(dose_params)
    has_been_saved = @dose.save

    if has_been_saved
      redirect_to cocktail_path(id: @cocktail.id)
    else
      # raise "Dose could not be saved because #{@dose.errors.full_messages}"
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    cocktail_id = Cocktail.find(@dose.cocktail_id)
    @dose.destroy
    redirect_back(fallback_location: cocktail_path)
    #redirect_to cocktail_path(id: cocktail_id)
  end


  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  def index
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/ingredient_helper.rb
module IngredientHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/cocktails/_form.html.erb
<div class="container">
  <%= simple_form_for(@cocktail) do |f| %>
  <div class="form-group">
    <%= f.input :name, placeholder: "Enter a cocktail name", html: {:class => 'form-control'} %>
    <%= f.input :category, placeholder: "Enter a cocktail category", html: {:class => 'form-control'} %>
    <%= f.input :alcoholic, placeholder: "Is it alcoholic?", html: {:class => 'form-control'} %>
    <%= f.input :instructions, as: :text, html: {:class => 'form-control'} %>
    <div class="form-inline">
      <%= f.input :difficulty, as: :radio_buttons, collection: 0..5 %>
    </div>
    <%= f.input :photos, as: :attachinary %>
  </div>
  <%= f.submit %>
  <% end %>
</div>

app/views/cocktails/edit.html.erb
<%= render 'form' %>

app/views/cocktails/index.html.erb
<div class="banner" style="background:  linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('<%= cl_image_path("flaming_cocktails_xxfxfa.jpg")%>');">
  <div class="banner-content">
    <h1>Welcome to Mr. Cocktail</h1>
    <p>Find new ways to mix your poison ;)</p>
    <div class="search-form">
      <%= form_tag(search_path, :method => "get", id: "search-form", :class => "form-inline text-center") do %>
        <%= text_field_tag :search, params[:search], placeholder: "Search Cocktails", :class => "form-control" %>
        <%= submit_tag "Search", :name => nil, :class => "btn btn-primary btn-lg" %>
      <% end %>
    </div>
  </div>
</div>
<div class="container">
  <div class="category-carousel">
    <div class="header">
      <h3>Explore cocktails recipes</h3>
      <%= link_to "See All >", "#", class: "link" %>
    </div>
  </div>
  <div class="row">
    <% @cocktails.each do |cocktail| %>
    <div class="col-xs-12 col-sm-6 col-md-3">
      <div class="card">
        <div class="card-body" style="background-image: linear-gradient(rgba(0,0,0,0.6), rgba(0,0,0,0.2)), url(<%= cl_image_path cocktail.photos.last.path %>);">
          <span class="card-category"><%= cocktail.category %></span>
          <div class="card-description">
            <h2><%= cocktail.name %></h2>
            <p><%= truncate(cocktail.instructions, :length => 30) %></p>
          </div>
          <img class="card-user avatar avatar-large" src="images/jad.png">
          <%= link_to cocktail.name, cocktail_path(id: cocktail.id), class: "card-link" %>
        </div>
        <div class="card-footer">
          <p>Posted on <%= cocktail.created_at.strftime("%d/%m/%Y") %></p>
          <div class="controls">
            <a href="#"><i class="fa fa-star"></i></a>
            <a href="#"><i class="fa fa-heart"></i></a>
            <a href="#"><i class="fa fa-share"></i></a>
          </div>
        </div>
      </div>
    </div>
    <% end %>
  </div>

  <h3>Most voted cocktails</h3>
  <div class="product">
    <div class='product-upvote'>
      <div class="product-arrow"></div>
      <div class='product-count'>95</div>
    </div>
    <div class='product-body'>
      <h3>Kudoz</h3>
      <p>Best job offers on your phone</p>
    </div>
    <ul class="list-inline product-controls hidden-sm hidden-xs">
      <li><a href=""><i class="fa fa-heart"></i></a></li>
      <li><a href=""><i class="fa fa-share"></i></a></li>
      <li><a href=""><i class="fa fa-star"></i></a></li>
    </ul>
  </div>

</div>

app/views/cocktails/profile.html.erb
<div class="profile-header-wrapper">
  <!-- Profile header -->
  <div class="profile-header-info text-center">
    <img src="http://lewagon.github.io/html-css-challenges/11-profile-with-tabs/images/papillard.jpeg" alt="Gil's profile" class="avatar-large">
    <h1>@darkarraylord</h1>
    <h2>Co founder @Vendimo</h2>
  </div>
  <!-- profile tabs -->
  <div class="tabs">
    <a class="tab active" href="#">
      <h3>350</h3>
      <p>Followers</p>
    </a>
    <a class="tab" href="#">
      <h3>456</h3>
      <p>Following</p>
    </a>
    <a class="tab" href="#">
      <h3>189</h3>
      <p>Upvoted</p>
    </a>
    <a class="tab" href="#">
      <h3>13</h3>
      <p>Submitted</p>
    </a>
  </div>
</div>
<div class="container">
  <% @cocktails.each do |cocktail| %>
  <div class="product">
    <div class='product-upvote'>
      <div class="product-arrow"></div>
      <div class='product-count'>8</div>
    </div>
    <img src="kudoz.jpg" alt="kudoz" class="product-image hidden-xs">
    <div class='product-body'>
      <h3><%= cocktail.name %></h3>
      <p><%= truncate(cocktail.instructions , :length => 50)%></p>
    </div>
    <ul class="list-inline product-controls hidden-sm hidden-xs">
      <li><a href=""><i class="glyphicon glyphicon-glass"></i></a></li>
      <li><a href=""><i class="glyphicon glyphicon-pencil"></i></a></li>
      <li>
        <%= link_to cocktail_path(id: cocktail.id), method: :delete do %>
          <i class="glyphicon glyphicon-remove"></i>
          <% end %>
      </li>
    </ul>
  </div>
<% end %>
</div>

app/views/cocktails/search.html.erb
<div class="container">
  <div class="alert alert-info" role="alert">
      Your search <%= params[:search].downcase.strip %> resulted in <%= @cocktails.count %> cocktails
    </div>
  <div class="results">
    <% @cocktails.each do |cocktail|  %>
    <div class="row">
    <div class="col-xs-3">
      <%= cl_image_tag cocktail.photos.last.path, :crop => "fill", :width => 200, :height => 200 %></div>
      <div class="col-xs-6">
        <h3><%= link_to cocktail.name, cocktail_path(id: cocktail.id) %></h3>
        <%= cocktail.instructions %>
      </div>
      <div class="col-xs-3">
      date and other actions</div>
    </div>
  </div>
    <% end %>

  </div>
</div>

app/views/cocktails/show.html.erb
  <div class="cocktail-head" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('http://res.cloudinary.com/gilcpd/image/upload/<% @cocktail.photos.each do |photo| %><%= photo.path %><% end %>');">
    <div class="cocktail-category"><%= @cocktail.category %></div>
    <div class="cocktail-description">
      <h2><%= @cocktail.name %></h2>
      <p>Very cool city, the best</p>
    </div>
    <div class="cocktail-actions">
      <ul class="list-inline">
        <a href="#"><i class="fa fa-instagram"></i></a>
        <a href="#"><i class="fa fa-facebook"></i></a>
        <a href="#"><i class="fa fa-twitter"></i></a>
        <a href="#"><i class="fa fa-heart"></i></a>
      </ul>
    </div>
    <a href="#"><img class="cocktail-user" src="https://kitt.lewagon.com/placeholder/users/tgenaitay"></a>
  </div>
  <!-- end cocktail profile-->


<div class="container">
  <div class="doses">
      <h2><%= @cocktail.name %> - <small><%= @cocktail.alcoholic %></small></h2>
      <p> <strong>Instructions</strong> <%= @cocktail.instructions %></p>
    <div class="data-block">

      <ul class="list">
        <% @cocktail.doses.each do |dose| %>
        <li>
          <%= dose.description %> of <%= dose.ingredient.name %>
          <%= link_to "Remove this dose", dose_path(id: dose.id), method: :delete %>
        </li>
        <% end %>
      </ul>
      <%= link_to  new_cocktail_dose_path(cocktail_id: @cocktail.id) do %>
      <span><i class="fa fa-heart"></i> Add another dose</span>
      <% end %>

    </div>
    <div class="data-block">
      <% @cocktail.comments.each do |comment|  %>
        <div class="message">
          <img class="avatar-large" src="https://kitt.lewagon.com/placeholder/users/gabriel-dehan">
          <div class="message-name">
            <h3>Gab Dehan</h3>
            <p>10/07/17</p>
          </div>
          <div class="message-body">
            <p><strong>I am not sure yet!</strong></p>
            <p>
              <%= comment.comment %>
            </p>
          </div>
          <div class="message-status">
            <p class="status pending">Pending</p>
            <p class="price">€345</p>
          </div>
        </div>
      <% end %>
    <%= link_to "add comment", new_cocktail_comment_path(cocktail_id: @cocktail.id)%>
    </div>
    <!-- end of cocktail data-->
  </div>
</div>

app/views/comments/_form.html.erb
<%= simple_form_for([@cocktail, @comment]) do |f| %>
  <%= f.input(:comment) %>
  <%= f.submit %>
<% end %>

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/new.html.erb
<%= render 'form' %>

app/views/doses/_form.html.erb
<%= simple_form_for([@cocktail, @dose]) do |f| %>
  <%= f.input(:description) %>
  <%= f.input(:ingredient_id, { collection: Ingredient.all }) %>
  <%= f.submit %>
<% end %>

app/views/doses/index.html.erb
<h1>Doses#index</h1>
<p>Find me in app/views/doses/index.html.erb</p>

app/views/doses/show.html.erb
<h1>Doses#show</h1>
<p>Find me in app/views/doses/show.html.erb</p>

app/views/ingredients/index.html.erb
<h1>Ingredients#index</h1>
<p>Find me in app/views/ingredients/index.html.erb</p>

app/views/ingredients/show.html.erb
<h1>Ingredients#show</h1>
<p>Find me in app/views/ingredients/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="navbar-wagon">
      <!-- Logo -->
      <%= link_to root_path, class: "navbar-wagon-brand" do %>
        <%= image_tag "logo.png" %>
      <% end %>


      <!-- Right Navigation -->
      <div class="navbar-wagon-right hidden-xs hidden-sm">
        <%= form_tag(search_path, :method => "get", id: "search-form", :class => "navbar-form navbar-right") do %>
          <%= text_field_tag :search, params[:search], placeholder: "Search Cocktails", :class => "form-control" %>
          <%= submit_tag "Search", :name => nil, :class => "btn btn-primary btn-lg" %>
        <% end %>
        <!-- Links -->
        <%= link_to "Add Cocktail", new_cocktail_path, class: "navbar-wagon-item navbar-wagon-link" %>
        <%= link_to "Cocktails", cocktails_path, class: "navbar-wagon-item navbar-wagon-link" %>
        <%= link_to "Messages", "#", class: "navbar-wagon-item navbar-wagon-link" %>

        <!-- Avatar with dropdown menu -->
        <div class="navbar-wagon-item">
          <div class="dropdown">
            <%= image_tag "http://placehold.it/30x30", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
            <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
              <li>
                <%= link_to profile_path do %>
                  <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
                <% end %>
              </li>
              <li>
                <%= link_to "#" do %>
                  <i class="fa fa-home"></i>  <%= t(".profile", default: "Account Settings") %>
                <% end %>
              </li>
            </ul>
          </div>
        </div>
      </div>

      <!-- Dropdown list appearing on mobile only -->
      <div class="navbar-wagon-item hidden-md hidden-lg">
        <div class="dropdown">
          <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li><%= link_to "Add Cocktail", new_cocktail_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
            <li><%= link_to "Cocktails", cocktails_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
            <li><%= link_to "Messages", "#", class: "navbar-wagon-item navbar-wagon-link" %></li>
            <li>
              <%= link_to profile_path do %>
                  <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
                <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                  <i class="fa fa-home"></i>  <%= t(".profile", default: "Account Settings") %>
                <% end %>
            </li>
          </ul>
        </div>
      </div>
    </div>

    <%= yield %>
    <%= cloudinary_js_config %> <!-- Append this after the main `javascript_include_tag`. -->
    <div class="footer">
      <div class="footer-links">
        <a href="#"><i class="fa fa-github"></i></a>
        <a href="#"><i class="fa fa-instagram"></i></a>
        <a href="#"><i class="fa fa-facebook"></i></a>
        <a href="#"><i class="fa fa-twitter"></i></a>
        <a href="#"><i class="fa fa-linkedin"></i></a>
      </div>
      <div class="footer-copyright">
        This footer is made with <i class="fa fa-heart"></i> at Le Wagon
      </div>
    </div>
  </body>
</html>